"""Adding the 'core' attribute

Revision ID: a96571483ebe
Revises: 49b483773721
Create Date: 2025-03-26 22:28:15.539749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a96571483ebe'
down_revision: Union[str, None] = '49b483773721'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodes', sa.Column('is_core', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nodes', 'is_core')
    # ### end Alembic commands ###
